/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-04-01 at 23:47:39 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.hefesoftpharmacy.model;

/**
 * Model definition for VisitaRealizada.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class VisitaRealizada extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime fechaYHora;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idPanel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key panel;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public VisitaRealizada setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFechaYHora() {
    return fechaYHora;
  }

  /**
   * @param fechaYHora fechaYHora or {@code null} for none
   */
  public VisitaRealizada setFechaYHora(com.google.api.client.util.DateTime fechaYHora) {
    this.fechaYHora = fechaYHora;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public VisitaRealizada setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdPanel() {
    return idPanel;
  }

  /**
   * @param idPanel idPanel or {@code null} for none
   */
  public VisitaRealizada setIdPanel(java.lang.Long idPanel) {
    this.idPanel = idPanel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getPanel() {
    return panel;
  }

  /**
   * @param panel panel or {@code null} for none
   */
  public VisitaRealizada setPanel(Key panel) {
    this.panel = panel;
    return this;
  }

  @Override
  public VisitaRealizada set(String fieldName, Object value) {
    return (VisitaRealizada) super.set(fieldName, value);
  }

  @Override
  public VisitaRealizada clone() {
    return (VisitaRealizada) super.clone();
  }

}
