/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-03-26 at 00:05:15 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.hefesoftpharmacy.model;

/**
 * Model definition for Ciclo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Ciclo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean activo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer diasHabiles;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer diasReunionCiclo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime fechaInicial;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime fechaReunionCiclo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String idUPES;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer plazoRegistrarPedido;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer plazoReportarVisita;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getActivo() {
    return activo;
  }

  /**
   * @param activo activo or {@code null} for none
   */
  public Ciclo setActivo(java.lang.Boolean activo) {
    this.activo = activo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDiasHabiles() {
    return diasHabiles;
  }

  /**
   * @param diasHabiles diasHabiles or {@code null} for none
   */
  public Ciclo setDiasHabiles(java.lang.Integer diasHabiles) {
    this.diasHabiles = diasHabiles;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDiasReunionCiclo() {
    return diasReunionCiclo;
  }

  /**
   * @param diasReunionCiclo diasReunionCiclo or {@code null} for none
   */
  public Ciclo setDiasReunionCiclo(java.lang.Integer diasReunionCiclo) {
    this.diasReunionCiclo = diasReunionCiclo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFechaInicial() {
    return fechaInicial;
  }

  /**
   * @param fechaInicial fechaInicial or {@code null} for none
   */
  public Ciclo setFechaInicial(com.google.api.client.util.DateTime fechaInicial) {
    this.fechaInicial = fechaInicial;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFechaReunionCiclo() {
    return fechaReunionCiclo;
  }

  /**
   * @param fechaReunionCiclo fechaReunionCiclo or {@code null} for none
   */
  public Ciclo setFechaReunionCiclo(com.google.api.client.util.DateTime fechaReunionCiclo) {
    this.fechaReunionCiclo = fechaReunionCiclo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Ciclo setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdUPES() {
    return idUPES;
  }

  /**
   * @param idUPES idUPES or {@code null} for none
   */
  public Ciclo setIdUPES(java.lang.String idUPES) {
    this.idUPES = idUPES;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Ciclo setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPlazoRegistrarPedido() {
    return plazoRegistrarPedido;
  }

  /**
   * @param plazoRegistrarPedido plazoRegistrarPedido or {@code null} for none
   */
  public Ciclo setPlazoRegistrarPedido(java.lang.Integer plazoRegistrarPedido) {
    this.plazoRegistrarPedido = plazoRegistrarPedido;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPlazoReportarVisita() {
    return plazoReportarVisita;
  }

  /**
   * @param plazoReportarVisita plazoReportarVisita or {@code null} for none
   */
  public Ciclo setPlazoReportarVisita(java.lang.Integer plazoReportarVisita) {
    this.plazoReportarVisita = plazoReportarVisita;
    return this;
  }

  @Override
  public Ciclo set(String fieldName, Object value) {
    return (Ciclo) super.set(fieldName, value);
  }

  @Override
  public Ciclo clone() {
    return (Ciclo) super.clone();
  }

}
