/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-03-26 at 00:05:15 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.hefesoftpharmacy.model;

/**
 * Model definition for Medicos.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Medicos extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String apellidos;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cedula;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cordenadas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String direccion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idEntidad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String imagenUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombres;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String telefono;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("telefono_Celular")
  private java.lang.String telefonoCelular;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getApellidos() {
    return apellidos;
  }

  /**
   * @param apellidos apellidos or {@code null} for none
   */
  public Medicos setApellidos(java.lang.String apellidos) {
    this.apellidos = apellidos;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCedula() {
    return cedula;
  }

  /**
   * @param cedula cedula or {@code null} for none
   */
  public Medicos setCedula(java.lang.String cedula) {
    this.cedula = cedula;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCordenadas() {
    return cordenadas;
  }

  /**
   * @param cordenadas cordenadas or {@code null} for none
   */
  public Medicos setCordenadas(java.lang.String cordenadas) {
    this.cordenadas = cordenadas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDireccion() {
    return direccion;
  }

  /**
   * @param direccion direccion or {@code null} for none
   */
  public Medicos setDireccion(java.lang.String direccion) {
    this.direccion = direccion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Medicos setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Medicos setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdEntidad() {
    return idEntidad;
  }

  /**
   * @param idEntidad idEntidad or {@code null} for none
   */
  public Medicos setIdEntidad(java.lang.Long idEntidad) {
    this.idEntidad = idEntidad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImagenUrl() {
    return imagenUrl;
  }

  /**
   * @param imagenUrl imagenUrl or {@code null} for none
   */
  public Medicos setImagenUrl(java.lang.String imagenUrl) {
    this.imagenUrl = imagenUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombres() {
    return nombres;
  }

  /**
   * @param nombres nombres or {@code null} for none
   */
  public Medicos setNombres(java.lang.String nombres) {
    this.nombres = nombres;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelefono() {
    return telefono;
  }

  /**
   * @param telefono telefono or {@code null} for none
   */
  public Medicos setTelefono(java.lang.String telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelefonoCelular() {
    return telefonoCelular;
  }

  /**
   * @param telefonoCelular telefonoCelular or {@code null} for none
   */
  public Medicos setTelefonoCelular(java.lang.String telefonoCelular) {
    this.telefonoCelular = telefonoCelular;
    return this;
  }

  @Override
  public Medicos set(String fieldName, Object value) {
    return (Medicos) super.set(fieldName, value);
  }

  @Override
  public Medicos clone() {
    return (Medicos) super.clone();
  }

}
