/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-04-01 at 23:47:39 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.hefesoftpharmacy.model;

/**
 * Model definition for Panel.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Panel extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean activo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean alta;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer aprobado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean baja;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String categoria;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key ciclo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Ciclo cicloEntity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long comodin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer contactosActual;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer contactosNuevo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer contactosOriginal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idCiclo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idEntidad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idUnidadVisita;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idUsuario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key unidadVisita;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private UnidadVisita unidadVisitaEntity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key usuario;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getActivo() {
    return activo;
  }

  /**
   * @param activo activo or {@code null} for none
   */
  public Panel setActivo(java.lang.Boolean activo) {
    this.activo = activo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAlta() {
    return alta;
  }

  /**
   * @param alta alta or {@code null} for none
   */
  public Panel setAlta(java.lang.Boolean alta) {
    this.alta = alta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAprobado() {
    return aprobado;
  }

  /**
   * @param aprobado aprobado or {@code null} for none
   */
  public Panel setAprobado(java.lang.Integer aprobado) {
    this.aprobado = aprobado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getBaja() {
    return baja;
  }

  /**
   * @param baja baja or {@code null} for none
   */
  public Panel setBaja(java.lang.Boolean baja) {
    this.baja = baja;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCategoria() {
    return categoria;
  }

  /**
   * @param categoria categoria or {@code null} for none
   */
  public Panel setCategoria(java.lang.String categoria) {
    this.categoria = categoria;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getCiclo() {
    return ciclo;
  }

  /**
   * @param ciclo ciclo or {@code null} for none
   */
  public Panel setCiclo(Key ciclo) {
    this.ciclo = ciclo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Ciclo getCicloEntity() {
    return cicloEntity;
  }

  /**
   * @param cicloEntity cicloEntity or {@code null} for none
   */
  public Panel setCicloEntity(Ciclo cicloEntity) {
    this.cicloEntity = cicloEntity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getComodin() {
    return comodin;
  }

  /**
   * @param comodin comodin or {@code null} for none
   */
  public Panel setComodin(java.lang.Long comodin) {
    this.comodin = comodin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getContactosActual() {
    return contactosActual;
  }

  /**
   * @param contactosActual contactosActual or {@code null} for none
   */
  public Panel setContactosActual(java.lang.Integer contactosActual) {
    this.contactosActual = contactosActual;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getContactosNuevo() {
    return contactosNuevo;
  }

  /**
   * @param contactosNuevo contactosNuevo or {@code null} for none
   */
  public Panel setContactosNuevo(java.lang.Integer contactosNuevo) {
    this.contactosNuevo = contactosNuevo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getContactosOriginal() {
    return contactosOriginal;
  }

  /**
   * @param contactosOriginal contactosOriginal or {@code null} for none
   */
  public Panel setContactosOriginal(java.lang.Integer contactosOriginal) {
    this.contactosOriginal = contactosOriginal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Panel setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Panel setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdCiclo() {
    return idCiclo;
  }

  /**
   * @param idCiclo idCiclo or {@code null} for none
   */
  public Panel setIdCiclo(java.lang.Long idCiclo) {
    this.idCiclo = idCiclo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdEntidad() {
    return idEntidad;
  }

  /**
   * @param idEntidad idEntidad or {@code null} for none
   */
  public Panel setIdEntidad(java.lang.Long idEntidad) {
    this.idEntidad = idEntidad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdUnidadVisita() {
    return idUnidadVisita;
  }

  /**
   * @param idUnidadVisita idUnidadVisita or {@code null} for none
   */
  public Panel setIdUnidadVisita(java.lang.Long idUnidadVisita) {
    this.idUnidadVisita = idUnidadVisita;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdUsuario() {
    return idUsuario;
  }

  /**
   * @param idUsuario idUsuario or {@code null} for none
   */
  public Panel setIdUsuario(java.lang.Long idUsuario) {
    this.idUsuario = idUsuario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getUnidadVisita() {
    return unidadVisita;
  }

  /**
   * @param unidadVisita unidadVisita or {@code null} for none
   */
  public Panel setUnidadVisita(Key unidadVisita) {
    this.unidadVisita = unidadVisita;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public UnidadVisita getUnidadVisitaEntity() {
    return unidadVisitaEntity;
  }

  /**
   * @param unidadVisitaEntity unidadVisitaEntity or {@code null} for none
   */
  public Panel setUnidadVisitaEntity(UnidadVisita unidadVisitaEntity) {
    this.unidadVisitaEntity = unidadVisitaEntity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getUsuario() {
    return usuario;
  }

  /**
   * @param usuario usuario or {@code null} for none
   */
  public Panel setUsuario(Key usuario) {
    this.usuario = usuario;
    return this;
  }

  @Override
  public Panel set(String fieldName, Object value) {
    return (Panel) super.set(fieldName, value);
  }

  @Override
  public Panel clone() {
    return (Panel) super.clone();
  }

}
